/********************************************************************
* src/GRootWriterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GRootWriterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGRootWriterDict();
extern void G__cpp_setup_inheritanceGRootWriterDict();
extern void G__cpp_setup_typetableGRootWriterDict();
extern void G__cpp_setup_memvarGRootWriterDict();
extern void G__cpp_setup_globalGRootWriterDict();
extern void G__cpp_setup_memfuncGRootWriterDict();
extern void G__cpp_setup_funcGRootWriterDict();
extern void G__set_cpp_environmentGRootWriterDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/GRootWriter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GRootWriterDictLN_TClass;
extern G__linked_taginfo G__GRootWriterDictLN_TBuffer;
extern G__linked_taginfo G__GRootWriterDictLN_TMemberInspector;
extern G__linked_taginfo G__GRootWriterDictLN_ROOT;
extern G__linked_taginfo G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__GRootWriterDictLN_string;
extern G__linked_taginfo G__GRootWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GRootWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GRootWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GRootWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GRootWriterDictLN_TTree;
extern G__linked_taginfo G__GRootWriterDictLN_TFile;
extern G__linked_taginfo G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__GRootWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__GRootWriterDictLN_ROOTcLcLMath;
extern G__linked_taginfo G__GRootWriterDictLN_ROOTcLcLMathcLcLDisplacementVector3DlEROOTcLcLMathcLcLCartesian3DlEdoublegRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR;
extern G__linked_taginfo G__GRootWriterDictLN_GRootWriter;

/* STUB derived class for protected member access */
