/********************************************************************
* src/GRootDCNavigatorDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error src/GRootDCNavigatorDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableGRootDCNavigatorDict();
extern void G__cpp_setup_inheritanceGRootDCNavigatorDict();
extern void G__cpp_setup_typetableGRootDCNavigatorDict();
extern void G__cpp_setup_memvarGRootDCNavigatorDict();
extern void G__cpp_setup_globalGRootDCNavigatorDict();
extern void G__cpp_setup_memfuncGRootDCNavigatorDict();
extern void G__cpp_setup_funcGRootDCNavigatorDict();
extern void G__set_cpp_environmentGRootDCNavigatorDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "include/GRootDCNavigator.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__GRootDCNavigatorDictLN_TClass;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_TBuffer;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_TMemberInspector;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_TGeoManager;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_TGeoMaterial;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_TGeoMedium;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_TGeoVolume;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_TVector3;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_GDCTelescope;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_GDCGeometry;
extern G__linked_taginfo G__GRootDCNavigatorDictLN_GRootDCNavigator;

/* STUB derived class for protected member access */
