/********************************************************************
* VCORSIKARunheader_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error VCORSIKARunheader_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableVCORSIKARunheader_Dict();
extern void G__cpp_setup_inheritanceVCORSIKARunheader_Dict();
extern void G__cpp_setup_typetableVCORSIKARunheader_Dict();
extern void G__cpp_setup_memvarVCORSIKARunheader_Dict();
extern void G__cpp_setup_globalVCORSIKARunheader_Dict();
extern void G__cpp_setup_memfuncVCORSIKARunheader_Dict();
extern void G__cpp_setup_funcVCORSIKARunheader_Dict();
extern void G__set_cpp_environmentVCORSIKARunheader_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "inc/VCORSIKARunheader.h"
#include "./inc/VCORSIKARunheader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__VCORSIKARunheader_DictLN_TClass;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_TBuffer;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_TMemberInspector;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_TObject;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_TNamed;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_basic_ostreamlEcharcOchar_traitslEchargRsPgR;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__VCORSIKARunheader_DictLN_VCORSIKARunheader;

/* STUB derived class for protected member access */
